version: '3.8'

services:
  costa-company-api:
    image: postgres
    container_name: costa-company-api
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=costacompany
      - POSTGRES_PASSWORD=costacompany123
      - POSTGRES_DB=costacompany

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD={REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
